### ISSUE TITLE
Modifed SELinux rules

### ISSUE THREAD

**Issue by danielphan2003** [chenxiaolong/MSD#2]
I found out that MSD can change SELinux rules, which some bank apps don't like. You can test this using https://huskydg.github.io/blog/detect_magisk_xposed.html#detect-selinux-rules.

I used Memory Detector from the same author to confirm, but unfortunately the repo is removed and I obtained the apk from Telegram. If you want, I can provide one here.

**Comment by chenxiaolong** [comment]
Thanks for reporting this. I don't plan on playing the cat-and-mouse game to try and hide MSD, but I'm happy to help troubleshoot a little bit in case there's an easy workaround.

Just to make sure it is actually related to the SELinux policy, please try this:

1. Uninstall MSD
2. Confirm that nothing is detected
3. Extract `msd-tool.arm64-v8a` from MSD's zip
4. Run `./msd-tool.arm64-v8a sepatch -ST` as root (via adb or Termux)
5. Check if it detects SELinux modifications

If it detects that, then it really is something with the policy. Otherwise, I'm guessing it's detecting MSD's daemon process or bind mount.
